[server]
enableXsrfProtection = false
headless = true
port = 8051
enableCORS = false

[theme]
base = "dark"
primaryColor = "#0366d6"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#FAFAFA"
font = "sans serif"
